stages:
  - test
  - release

eslint:
  stage: test
  image: registry.gitlab.com/scrumble/gitlab-ci:8.2
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development-*" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  script:
    - npm ci
    - npm run eslint

test:
  stage: test
  image: registry.gitlab.com/scrumble/gitlab-ci:8.2
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development-*" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  script:
    - npm ci
    - npm test

publish:
  stage: release
  image: registry.gitlab.com/scrumble/gitlab-ci:8.2
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
      allow_failure: true
  variables:
    RELEASE_ACCESS: 'restricted'
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - npm install
    - |
      PACKAGE_VERSION=$(node -p "require('./package.json').version")
      if [ "$PACKAGE_VERSION" != "$CI_COMMIT_TAG" ]; then
        echo "Version in package.json ($PACKAGE_VERSION) does not match the tag ($CI_COMMIT_TAG)."
        exit 1
      fi
    - npm run build
    - npm publish --access $RELEASE_ACCESS